# Generated by Django 3.1.4 on 2022-12-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainapp', '0002_auto_20221207_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainticket',
            name='train_no',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
